/*
 * SPDX-License-Identifier: Apache-2.0
 *
 * The OpenSearch Contributors require contributions made to
 * this file be licensed under the Apache-2.0 license or a
 * compatible open source license.
 */

package org.opensearch.remotestore;

import com.carrotsearch.randomizedtesting.annotations.ThreadLeakFilters;
import org.opensearch.action.bulk.BulkRequest;
import org.opensearch.action.bulk.BulkResponse;
import org.opensearch.action.index.IndexRequest;
import org.opensearch.cluster.metadata.RepositoryMetadata;
import org.opensearch.cluster.service.ClusterService;
import org.opensearch.common.blobstore.BlobStore;
import org.opensearch.common.blobstore.fs.FsBlobStore;
import org.opensearch.common.settings.Settings;
import org.opensearch.core.xcontent.NamedXContentRegistry;
import org.opensearch.env.Environment;
import org.opensearch.index.IndexSettings;
import org.opensearch.index.store.CountingFsBlobContainer;
import org.opensearch.index.store.CountingFsBlobStore;
import org.opensearch.index.translog.TranslogArchiveTimerThreadLeakFilter;
import org.opensearch.indices.RemoteStoreSettings;
import org.opensearch.indices.recovery.RecoverySettings;
import org.opensearch.plugins.Plugin;
import org.opensearch.plugins.RepositoryPlugin;
import org.opensearch.repositories.Repository;
import org.opensearch.repositories.fs.FsRepository;
import org.opensearch.test.OpenSearchIntegTestCase;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.stream.Collectors;
import java.util.stream.Stream;

import static org.opensearch.test.hamcrest.OpenSearchAssertions.assertAcked;

/**
 * Integration test that verifies the number of S3-equivalent operations (LIST, GET, PUT, DELETE)
 * generated by the translog archive feature during a bulk indexing workload.
 *
 * <p>Uses a local filesystem-backed repository with a counting wrapper to intercept and count
 * all BlobContainer operations. Captures LIST stack traces to identify root causes of excess LISTs.</p>
 *
 * Setup: single data node + cluster-manager, 1 index with 5 primary shards (0 replicas),
 * FIXED path prefix, translog + segment archive enabled, default buffer_interval (650ms).
 */
@ThreadLeakFilters(filters = TranslogArchiveTimerThreadLeakFilter.class)
@OpenSearchIntegTestCase.ClusterScope(scope = OpenSearchIntegTestCase.Scope.TEST, numDataNodes = 0)
public class TranslogArchiveS3OpsIT extends BaseRemoteStoreRestoreIT {

    private static final String INDEX_NAME = "s3ops-test";
    private static final int NUM_SHARDS = 3;
    private static final int NUM_THREADS = 5;
    private static final int ITERATIONS_PER_THREAD = 100;  // 5 threads × 100 iterations × 10 docs = 5K docs
    private static final int BULK_SIZE = 10;

    // ==================== Custom counting plugin ====================

    /** Plugin that registers a counting FS repository type. */
    public static class CountingFsRepositoryPlugin extends Plugin implements RepositoryPlugin {
        public static final String TYPE = "counting_fs";

        @Override
        public Map<String, Repository.Factory> getRepositories(
            Environment env,
            NamedXContentRegistry namedXContentRegistry,
            ClusterService clusterService,
            RecoverySettings recoverySettings
        ) {
            return Collections.singletonMap(
                TYPE,
                metadata -> new CountingFsRepository(metadata, env, namedXContentRegistry, clusterService, recoverySettings)
            );
        }
    }

    /** FsRepository that wraps the blob store with a CountingFsBlobStore. */
    public static class CountingFsRepository extends FsRepository {
        public CountingFsRepository(
            RepositoryMetadata metadata,
            Environment env,
            NamedXContentRegistry namedXContentRegistry,
            ClusterService clusterService,
            RecoverySettings recoverySettings
        ) {
            super(metadata, env, namedXContentRegistry, clusterService, recoverySettings);
        }

        @Override
        protected BlobStore createBlobStore() throws Exception {
            FsBlobStore original = (FsBlobStore) super.createBlobStore();
            return new CountingFsBlobStore(original.bufferSizeInBytes(), original.path(), false);
        }
    }

    // ==================== Plugin + settings overrides ====================

    @Override
    protected Collection<Class<? extends Plugin>> nodePlugins() {
        // Add our counting plugin; don't add MockFsRepositoryPlugin (we use counting_fs instead)
        return Stream.concat(
            super.nodePlugins().stream(),
            Stream.of(CountingFsRepositoryPlugin.class)
        ).collect(Collectors.toList());
    }

    @Override
    protected Settings nodeSettings(int nodeOrdinal) {
        // Init repo paths (same as base class)
        if (segmentRepoPath == null || translogRepoPath == null) {
            segmentRepoPath = randomRepoPath().toAbsolutePath();
            translogRepoPath = randomRepoPath().toAbsolutePath();
        }
        return Settings.builder()
            .put(super.nodeSettings(nodeOrdinal))
            .put(
                remoteStoreClusterSettings(
                    REPOSITORY_NAME, segmentRepoPath, CountingFsRepositoryPlugin.TYPE,
                    REPOSITORY_2_NAME, translogRepoPath, CountingFsRepositoryPlugin.TYPE
                )
            )
            // Segment archive is a cluster-level setting
            .put(RemoteStoreSettings.CLUSTER_REMOTE_STORE_SEGMENT_ARCHIVE_ENABLED.getKey(), true)
            .build();
    }

    // Tell base class we're supplying our own cluster settings (so it doesn't overwrite them)
    {
        clusterSettingsSuppliedByTest = true;
    }

    // ==================== Test ====================

    /**
     * Index 100K docs with archive enabled, then measure and log S3-equivalent operation counts.
     */
    public void testS3OperationCountsDuringIndexing() throws Exception {
        internalCluster().startClusterManagerOnlyNode();
        internalCluster().startDataOnlyNode();
        ensureGreen();

        // Create index: 5 primary shards, 0 replicas, archive enabled, FIXED prefix
        assertAcked(
            client().admin().indices().prepareCreate(INDEX_NAME)
                .setSettings(
                    Settings.builder()
                        .put(remoteStoreIndexSettings(0, NUM_SHARDS))
                        .put(IndexSettings.INDEX_REMOTE_STORE_TRANSLOG_ARCHIVE_UPLOAD_ENABLED_SETTING.getKey(), true)
                        .put("index.number_of_shards", NUM_SHARDS)
                        .put("index.number_of_replicas", 0)
                        .build()
                )
        );
        ensureGreen(INDEX_NAME);

        // Reset counters after cluster/index setup
        CountingFsBlobContainer.resetCounters();
        long indexingStart = System.currentTimeMillis();

        // Index 100K docs: NUM_THREADS × ITERATIONS_PER_THREAD × BULK_SIZE
        logger.info("=== Starting indexing: {} threads × {} iterations × {} docs/bulk ===",
            NUM_THREADS, ITERATIONS_PER_THREAD, BULK_SIZE);

        ExecutorService executor = Executors.newFixedThreadPool(NUM_THREADS);
        CountDownLatch latch = new CountDownLatch(NUM_THREADS);
        AtomicInteger totalDocs = new AtomicInteger(0);

        for (int t = 0; t < NUM_THREADS; t++) {
            executor.submit(() -> {
                try {
                    for (int i = 0; i < ITERATIONS_PER_THREAD; i++) {
                        BulkRequest bulk = new BulkRequest();
                        for (int d = 0; d < BULK_SIZE; d++) {
                            bulk.add(
                                new IndexRequest(INDEX_NAME).source(
                                    Map.of("v", UUID.randomUUID().toString(), "ts", System.currentTimeMillis())
                                )
                            );
                        }
                        BulkResponse resp = client().bulk(bulk).actionGet();
                        if (resp.hasFailures()) {
                            logger.warn("Bulk failures: {}", resp.buildFailureMessage());
                        }
                        totalDocs.addAndGet(BULK_SIZE);
                    }
                } catch (Exception e) {
                    logger.error("Indexing thread error", e);
                } finally {
                    latch.countDown();
                }
            });
        }

        latch.await(5, TimeUnit.MINUTES);
        executor.shutdown();
        long elapsedMs = System.currentTimeMillis() - indexingStart;
        long elapsedSec = Math.max(1, elapsedMs / 1000);

        logger.info("=== Indexing complete: {} docs in {}ms ({} docs/s) ===",
            totalDocs.get(), elapsedMs, totalDocs.get() / elapsedSec);

        // Flush to settle all translog uploads (no force-merge — too slow with archive ON)
        client().admin().indices().prepareFlush(INDEX_NAME).get();

        // Wait briefly for uploads to settle
        Thread.sleep(2_000);

        // ---- Log counters (during indexing) ----
        long puts = CountingFsBlobContainer.putCount.get();
        long gets = CountingFsBlobContainer.getCount.get();
        long lists = CountingFsBlobContainer.listCount.get();
        long deletes = CountingFsBlobContainer.deleteCount.get();

        logger.info("=== S3 Op Counts during {}s indexing (all {} shards) ===", elapsedSec, NUM_SHARDS);
        logger.info("  PUT    = {} total  ({}/shard  {}/shard/s)",
            puts, puts / NUM_SHARDS, puts / NUM_SHARDS / elapsedSec);
        logger.info("  GET    = {} total  ({}/shard  {}/shard/s)",
            gets, gets / NUM_SHARDS, gets / NUM_SHARDS / elapsedSec);
        logger.info("  LIST   = {} total  ({}/shard  {}/shard/s)",
            lists, lists / NUM_SHARDS, lists / NUM_SHARDS / elapsedSec);
        logger.info("  DELETE = {} total  ({}/shard  {}/shard/s)",
            deletes, deletes / NUM_SHARDS, deletes / NUM_SHARDS / elapsedSec);
        logger.info("  LIST/PUT ratio = {}", puts > 0 ? String.format("%.2f", (double) lists / puts) : "N/A");
        logger.info("  GET/PUT ratio  = {}", puts > 0 ? String.format("%.2f", (double) gets / puts) : "N/A");

        // ---- Now capture LIST stack traces during an idle window ----
        // Note: gc_interval minimum is 1m so we can't set it lower here.
        // The idle window captures steady-state background operations (translog timer, segment GC etc.)
        logger.info("=== Enabling LIST stack trace capture (idle window 15s) ===");
        CountingFsBlobContainer.resetCounters();
        CountingFsBlobContainer.captureListStacks = true;
        Thread.sleep(15_000);
        CountingFsBlobContainer.captureListStacks = false;

        logger.info("=== IDLE S3 Ops (15s, no indexing) ===");
        logger.info("  {}", CountingFsBlobContainer.countersToString());
        logger.info("  LIST stack traces captured: {}", CountingFsBlobContainer.listStackTraces.size());
        for (String trace : CountingFsBlobContainer.listStackTraces) {
            logger.info("\n{}", trace);
        }

        // Sanity assertions
        assertEquals("Expected " + (NUM_THREADS * ITERATIONS_PER_THREAD * BULK_SIZE) + " docs",
            NUM_THREADS * ITERATIONS_PER_THREAD * BULK_SIZE, totalDocs.get());
        assertTrue("Should have PUT operations (ZIPs uploaded)", puts > 0);
        // LIST/PUT ratio should be reasonable (< 10x)
        if (puts > 0) {
            double listToPutRatio = (double) lists / puts;
            logger.info("LIST/PUT ratio = {}", String.format("%.2f", listToPutRatio));
            // Informational — not a hard assertion, let the test tell us the number
        }
    }
}
